# Generated by Django 4.0.2 on 2022-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='http://www.dirtyapronrecipes.com/home/', max_length=500),
        ),
    ]
