# Generated by Django 4.0.2 on 2022-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.59b8493ce8bc3e21038d9b85a44b6133?rik=VwcGq4PVCk2dvA&riu=http%3a%2f%2fwww.ukvisitorguide.cn%2fwp-content%2fuploads%2f2015%2f11%2fFood-placeholder.jpg&ehk=vLfv4oTMqt4NGoXjvXIWptKQZN3aCyg9btfYCj4%2b3Lc%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1', max_length=500),
        ),
    ]
